version: "3.9"

services:
  db:
    image: mysql:8.0.30
    restart: unless-stopped
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
 
  web:
    build: .
    container_name: web
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:8000 proxecto.wsgi:application 
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    
    depends_on:
      - db
